{% import 'macros/common.j2' as util with context %}
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: default
spec:
  ports:
  - port: 9010
  selector:
    app: mlflow
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mlflow
  namespace: default
  labels:
     app: mlflow
spec:
  selector:
    matchLabels:
      mlflow-node: pod
  template:
    metadata:
      name: mlflow
      labels:
        mlflow-node: pod
        app: mlflow
    spec:
      nodeSelector:
        mlflow:   active
        archType: amd64
      containers:
      - name: mlflow
        image: {{ util.image_name('mlflow') }}
        imagePullPolicy: Always
        command: ["mlflow", "server", "--backend-store-uri", "mysql://root:apulis#2019#wednesday@mysql.kube-system/mlflow", "--default-artifact-root", "file:///app/mlflow-data", "--port", "9010", "--host" ,"0.0.0.0"]
        ports:
        - containerPort: 9010
          hostPort:      9010
          name: main
        volumeMounts:
      volumes:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

