- name: 生成MYSQL密码
  set_fact:
    password: "{{ lookup('password', '{{base_dir}}/credentials/mysql.pwd chars=ascii_letters,digits,hexdigits length=16') }}"

- name: 生成Harbor密码
  set_fact:
    password: "{{ lookup('password', '{{base_dir}}/credentials/harbor.pwd chars=ascii_letters,digits,hexdigits length=16') }}"

- name: 生成Harbor database密码
  set_fact:
    password: "{{ lookup('password', '{{base_dir}}/credentials/harbor-db.pwd chars=ascii_letters,digits,hexdigits length=16') }}"

- name: 生成cluster ID
  set_fact:
    password: "{{ lookup('password', '{{base_dir}}/credentials/cluster-id chars=ascii_letters,digits') | to_uuid }}"
