{% import 'macros/common.j2' as util with context %}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: image-label-{{ arch_map[ansible_architecture] }}
  namespace: default
  labels:
     run: dlwsimage-label
spec:
  selector:
    matchLabels:
      image-label-node: pod
  template:
    metadata:
      name: image-label-{{ arch_map[ansible_architecture] }}
      labels:
        image-label-node: pod
        app: image-label-{{ arch_map[ansible_architecture] }}
    spec:
      {{ util.dns_policy() }}
      nodeSelector:
        image-label: active
        archType: {{ arch_map[ansible_architecture] }}
      containers:
      - name: image-label-{{ arch_map[ansible_architecture] }}
        image: {{ util.image_fullname('image-label') }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3085
          hostPort: 3085
          name: main
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
