kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: google-cadvisor
  namespace: default
spec:
  selector:
    matchLabels:
      cadvisor-node: pod
  template:
    metadata:
      name: google-cadvisor
      labels:
        cadvisor-node: pod
    spec:
      nodeSelector: 
        google-cadvisor: active
      containers:
      - name: cadvisor
        image: google/cadvisor:latest
        ports:
          - name: http
            containerPort: 8080
            hostPort: 4191
