piVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---

apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: kube-system
subsets:
  - addresses:
    - ip: 192.168.1.200
    ports:
    - port: 3306
