apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: {{ service['mysql']['port']}}
---

apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: kube-system
subsets:
  - addresses:
    - ip: {{ service['mysql']['host']}}
    ports:
    - port: {{ service['mysql']['port']}}
