- hosts: nfs-server
  roles:
    - { role: 'nfs', nfs_mode: 'server', when: "CLUSTER_STORAGE == 'nfs'" }

- hosts:
    - kube-master
    - kube-worker
  roles:
    - { role: "nfs", nfs_mode: 'client', when: "CLUSTER_STORAGE == 'nfs'" }

- hosts: ceph-server
  roles:
    - { role: "rook-ceph", ceph_mode: "server", when: "CLUSTER_STORAGE is defined and CLUSTER_STORAGE == 'ceph'" }

- hosts:
    - kube-master
    - kube-worker
  roles:
    - { role: "rook-ceph", ceph_mode: "client", when: "CLUSTER_STORAGE == 'ceph'" }