- hosts: kube-master
  roles:
    - { role: "kube-service", step: "render", sub_service: "/mysql"}

- hosts: cluster
  roles:
    - { role: "kube-service", step: "storage" }

- hosts: kube-master
  roles:
    - { role: "kube-service", step: "saml" }