- hosts: localhost
  any_errors_fatal: yes
  vars_prompt:
    name: "confirmation"
    prompt: 'Do you want to stop {{ sn if sn is defined else "all aiarts"}} service?(yes/no)'
    default: "no"
    private: no
  tasks:
    - name: First Check Confirmation
      fail: msg='Playbook stop {{ sn if sn is defined else "all aiarts"}} service action canceled'
      when: not (confirmation | bool)

- hosts: cluster
  roles:
    - { role: aiarts-service, step: "stop-service", service_name: '{{sn if sn is defined else ""}}'}
