kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: image-label-amd64
  namespace: default
  labels:
     run: dlwsimage-label
spec:
  selector:
    matchLabels:
      image-label-node: pod
  template:
    metadata:
      name: image-label-amd64
      labels:
        image-label-node: pod
        app: image-label-amd64
    spec:
      
      nodeSelector:
        image-label: active
        archType: amd64
      containers:
      - name: image-label-amd64
        image: harbor.apulis.cn:8443/aiarts_v1.5.0_rc8/apulistech/dlworkspace_image-label:latest

        imagePullPolicy: Always
        ports:
        - containerPort: 3085
          hostPort: 3085
          name: main
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
