{% import 'macros/common.j2' as util with context %}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kube-system
spec:
  ports:
  - port: {{service["postgres"]["port"]}}
    protocol: TCP
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kube-system
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        archType: {{ arch_map[ ansible_architecture ] }}
        postgres: active
      hostNetwork: true
      containers:
      - image: {{ util.image_fullname('postgresql', 'third') }}
        name: postgres
        env:
        - name: POSTGRES_USER
          value: {{service["postgres"]["username"]}}
        - name: POSTGRES_PASSWORD
          value: {{service["postgres"]["password"]}}
        ports:
        - containerPort: {{service["postgres"]["port"]}}
          name: postgres
        volumeMounts:
        - name: aiplatform-component-data-pvc
          mountPath: /var/lib/postgresql/data
          subPath: postgres/
      volumes:
      - name: aiplatform-component-data-pvc
        persistentVolumeClaim:
          claimName: aiplatform-component-data-pvc
