apiVersion: v1
kind: PersistentVolume
metadata:
  name: aiplatform-app-data-pv
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: app-data
  mountOptions:
    - rsize=8192
    - timeo=14
    - intr
    - tcp
  nfs:
    server: conip
    path: /data/nfs/pvc/aiplatform-app-data

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aiplatform-app-data-pvc
spec:
  storageClassName: app-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
