step: "render"
sub_service: ""

service:
  clusterId: "{{ lookup('file', '{{ base_dir }}/credentials/cluster-id') }}"
  kube_vip_address: "{{kube_vip_address}}"
  k8sAPIport: 6443
  defalt_virtual_cluster_name: platform
  master_token:
  nccl_ib_disable:
  vc_node_hard_assignment:
