service:
  nvidia-driver-path: "/opt/nvidia-driver/current"
  per_user_gpu_limit: "-1"

  enable_vc: true
  enable_avisuals: false

  inference:
    tensorflow:
      allowedImageVersions:
        - 1.15.0
        - 1.15.0-arm64
        - 1.15.0-gpu
        - 2.2.0
        - 2.2.0-arm64
        - 2.2.0-gpu
    apulisVision:
      allowedImageVersions:
        - 1.0.0
  defalt_virtual_cluster_device_type_list:
    - nvidia_gpu_amd64
  kube_custom_scheduler: false
  gpu_count_per_node: 1
  worker_node_num: 1
  gpu_type: nvidia
  defalt_virtual_cluster_name: platform
  enable_cpuworker: False
  default_cpurequest:
  default_cpulimit:
  default_memoryrequest:
  default_memorylimit:
  default_cpu_sku: Standard_D2s_v3
  sku_meta:
    default:
      memory_ratio: 0.8
      cpu_ratio: 0.8
      Standard_D2s_v3:
        memory_ratio: 0.9
        memory: 8
        cpu: 2
        cpu_ratio: 0.9

  enable_blobfuse: dalse

