- name: For each host, scan for its ssh public key
  shell: "ssh-keyscan {{ item }},`dig +short {{ item }}`"
  with_items: "{{ groups['cluster'] + [ansible_env['SSH_CLIENT'].split()|first] }}"
  register: ssh_known_host_results
  run_once: true
  ignore_errors: yes

- name: Add {{ user_name }} and docker group to system
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ user_name }}"
    - docker

- name: Add {{ user_name }} user to system
  user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    shell: /bin/bash
    generate_ssh_key: yes
    state: present
    groups: sudo,docker
    append: yes

- name: Add/update the public key in the known_hosts
  known_hosts:
    name: "{{ item.item }}"
    key: "{{ item.stdout }}"
    state: "present"
    path: "/home/{{user_name}}/.ssh/known_hosts"
  with_items: "{{ ssh_known_host_results.results }}"

- name: Change known_hosts owner and group
  file:
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
    path: "/home/{{user_name}}/.ssh/known_hosts"
  with_items: "{{ ssh_known_host_results.results }}"

- name: Set authorized key in alternate location
  authorized_key:
    state: present
    user: "{{ user_name }}"
    key: "{{ lookup('file', item) }}"
  with_items:
    - "{{base_dir}}/credentials/rsa/id_rsa.pub"
    - "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

- name: copy id_ssh_rsa files to node
  copy:
    src: "{{base_dir}}/credentials/rsa/{{item.file}}"
    dest: "/home/{{user_name}}/.ssh/{{item.file}}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "{{ item.perm }}"
  with_items:
    - { file: id_rsa, perm: '0600' }
    - { file: id_rsa.pub, perm: '0644' }
