- name: 生成MYSQL密码
  set_fact:
    password: "{{ lookup('password', 'credentials/mysql.pwd chars=ascii_letters,digits,hexdigits,punctuation length=16') }}"

- name: 生成Harbor密码
  set_fact:
    password: "{{ lookup('password', 'credentials/harbor.pwd chars=ascii_letters,digits,hexdigits,punctuation length=16') }}"

- name: 生成Harbor database密码
  set_fact:
    password: "{{ lookup('password', 'credentials/harbor-db.pwd chars=ascii_letters,digits,hexdigits,punctuation length=16') }}"