- block:
    - name: stop and disable chrony in Ubuntu
      service: name=chrony state=stopped enabled=no
      ignore_errors: true
      when: 'ansible_distribution in ["Ubuntu","Debian"]'
  when: "groups['chrony']|length > 0"