- name: 检查镜像是否存在
  docker_image_info:
    name:
      - "{{thirdparty_images['kibana']['name']}}:{{thirdparty_images['kibana']['tag']}}"
  register: result

- block:
  - name: 下发kibana镜像文件
    copy:
      src: "{{resource_dir}}/images/kibana.tar"
      dest: "/tmp/kibana.tar"
  
  - name: 导入kibana镜像
    docker_image:
      name: "{{thirdparty_images['kibana']['name']}}:{{thirdparty_images['kibana']['tag']}}"
      load_path: /tmp/kibana.tar
      source: load

  when: result.images | length == 0
  become: yes


- name: 确保目录存在
  file:
    path: "{{ manifest_dest }}/kibana"
    state: directory


- name: 渲染yaml文件
  template:
    src: templates/config.yaml.j2
    dest: "{{ manifest_dest }}/kibana/config.yaml"
  
- name: debug
  debug: msg="{{ groups['es-cluster'][0] }}"

- name: 启动kibana容器
  docker_container:
    name: "kibana"
    image: "{{thirdparty_images['kibana']['name']}}:{{thirdparty_images['kibana']['tag']}}"
    env:
      servername: "kibana"
      ELASTICSEARCH_HOSTS: "http://{{ groups['es-cluster'][0] }}:9200"
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"
    published_ports:
      - "5601:5601"
    networks:
      - name: "{{es_network}}"
    volumes:
      - "{{ manifest_dest }}/kibana/config.yaml:/usr/share/kibana/config/kibana.yml"
