- name: Ensure the directory exist
  file:
    path: credentials/rsa
    state: directory
  delegate_to: localhost

- name: Generate an OpenSSH keypair with the default values (2048 bits, rsa)
  community.crypto.openssh_keypair:
    path: credentials/rsa/id_rsa
    size: 2048
  delegate_to: localhost

- name: Add {{ user_name }} group to system
  user:
    name: "{{ user_name }}"
    state: present

- name: Add {{ user_name }} user to system
  user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    state: present

- name: Set authorized key in alternate location
  authorized_key:
    state: present
    user: "{{ user_name }}"
    key: "{{ lookup('file', 'credentials/rsa/id_rsa.pub') }}"

- name: copy id_ssh_rsa files to node
  copy:
    src: "credentials/rsa/{{item.file}}"
    dest: "/home/{{user_name}}/.ssh/{{item.file}}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "{{ item.perm }}"
  with_items:
    - { file: id_rsa, perm: '0644' }
    - { file: id_rsa.pub, perm: '0644' }
