- name: For each host, scan for its ssh public key
  shell: "ssh-keyscan {{ item }},`dig +short {{ item }}`"
  with_items: "{{ groups['cluster'] }}"
  register: ssh_known_host_results
  ignore_errors: yes

- name: Add {{ user_name }} group to system
  group:
    name: "{{ user_name }}"
    state: present

- name: Add {{ user_name }} user to system
  user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    generate_ssh_key: yes
    state: present

- name: Add/update the public key in the known_hosts
  known_hosts:
    name: "{{ item.item }}"
    key: "{{ item.stdout }}"
    state: "present"
    path: "/home/{{user_name}}/.ssh/known_hosts"
  with_items: "{{ ssh_known_host_results.results }}"

- name: Change known_hosts owner and group
  file:
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
    path: "/home/{{user_name}}/.ssh/known_hosts"
  with_items: "{{ ssh_known_host_results.results }}"


- name: Set authorized key in alternate location
  authorized_key:
    state: present
    user: "{{ user_name }}"
    key: "{{ lookup('file', 'credentials/rsa/id_rsa.pub') }}"

- name: copy id_ssh_rsa files to node
  copy:
    src: "credentials/rsa/{{item.file}}"
    dest: "/home/{{user_name}}/.ssh/{{item.file}}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "{{ item.perm }}"
  with_items:
    - { file: id_rsa, perm: '0600' }
    - { file: id_rsa.pub, perm: '0644' }
