- name: 在 node 节点创建相关目录
  file: path={{ item }} state=directory
  with_items:
    - /opt/kube/kube-system

# DNS文件中部分参数根据hosts文件设置而定，因此需要用template模块替换参数
- name: 准备 DNS的部署文件
  template: src={{ item }}.yaml.j2 dest=/opt/kube/kube-system/{{ item }}.yaml
  with_items:
    - coredns

- name: 获取所有已经创建的POD信息
  command: "{{ bin_dir }}/kubectl get pod --all-namespaces"
  register: pod_info
  run_once: true

- name: 创建{{ dns_backend }}部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/{{ dns_backend }}.yaml"
  run_once: true
  when:
    - '"coredns" not in pod_info.stdout'
    - 'dns_install == "yes"'
  ignore_errors: true