- include_tasks: arch-labels.yaml

- name: 设置Master可以被调度
  command: >-
        {{ bin_dir }}/kubectl uncordon {{ inventory_hostname }}
  when:
    - MASTER_AS_WORKER
    - inventory_hostname in groups['kube-master']

- name: 设置组内节点的标签
  command: >-
        {{ bin_dir }}/kubectl label node {{ inventory_hostname }} {{ item.1 }}=active --overwrite=true
  when: "{{ inventory_hostname in groups[item.0.group] }}"
  with_subelements:
    - "{{ group_labels }}"
    - labels