- include_tasks: arch-labels.yaml

- include_tasks: npu_node.yaml

- name: 设置Master可以被调度
  command: >-
        {{ bin_dir }}/kubectl uncordon {{ inventory_hostname }}
  when:
    - inventory_hostname in groups['kube-master']

- name: 设置组内节点的标签
  command: >-
        {{ bin_dir }}/kubectl label node {{ inventory_hostname }} {{ item.1 }} --overwrite=true
  when:
    - "{{ item.0.index is not defined }}"
    - "{{ inventory_hostname in groups[item.0.group] }}"
  with_subelements:
    - "{{ group_labels }}"
    - labels

- name: 设置组内指定节点的标签
  command: >-
    {{ bin_dir }}/kubectl label node {{ inventory_hostname }} {{ item.1 }} --overwrite=true
  when:
    - "{{ item.0.index is defined }}"
    - "{{ inventory_hostname == groups[item.0.group][item.0.index] }}"
  with_subelements:
    - "{{ group_labels }}"
    - labels
