# 判断 NPU 设备是否存在
- name: 判断 NPU 设备是否存在
  shell: "npu-smi info"
  register: NPU_VAR
  ignore_errors: true

- block:
    - name: Ensure the directory exist
      file:
        path: /etc/npu/
        state: directory

    - name: 下发npu_info_gen.py脚本文件
      copy:
        src: npu_info_gen.py
        dest: /etc/npu/npu_info_gen.py
      tags: upgrade_smi

    - name: 下发unit service
      copy:
        src: npu-smi.service
        dest: /etc/systemd/system/npu-smi.service
      tags: upgrade_smi

    - name: 开机启用npu-smi服务
      shell: systemctl enable npu-smi
      ignore_errors: true

    - name: 开启npu-smi服务
      shell: systemctl daemon-reload && systemctl restart npu-smi
      ignore_errors: true
      tags: upgrade_smi

  when:
    - NPU_VAR.rc == 0