# 判断 NPU 设备是否存在
- name: 判断 NPU 设备是否存在
  shell: "npu-smi info"
  register: NPU_VAR
  ignore_errors: true

- block:
    - name: 下发npu_info_gen.py脚本文件
      copy:
        src: npu_info_gen.py
        dest: /tmp/npu_info_gen.py

    - name: 执行npu_info_gen.py 文件
      script: /tmp/npu_info_gen.py
  when:
    - NPU_VAR.rc == 0