# 判断 NPU 设备是否存在
- name: 判断 NPU 设备是否存在
  shell: "npu-smi info"
  register: NPU_VAR
  ignore_errors: true

- block:
    - name: Ensure the directory exist
      file:
        path: /etc/npu/
        state: directory

    - name: 下发npu_info_gen.py脚本文件
      copy:
        src: npu_info_gen.py
        dest: /etc/npu/npu_info_gen.py

    - name: 执行npu_info_gen.py 文件
      shell: "(cd /; python3 /etc/npu/npu_info_gen.py >/dev/null 2>&1 &)"
      when:
        - '"python3" in ansible_facts["discovered_interpreter_python"]'

    - name: 执行npu_info_gen.py 文件
      shell: "python /etc/npu/npu_info_gen.py >/dev/null 2>&1 &"
      when:
        - '"python3" not in ansible_facts["discovered_interpreter_python"]'
  when:
    - NPU_VAR.rc == 0