- name: update repositories cache and install NFS
  shell: "apt update && apt install -y nfs-common"
  when:
    - 'INSTALL_SOURCE == "online"'
    - "ansible_os_family == 'Debian'"

# tasks file for roles/nfs-mount
- import_tasks: offline-deb.yaml
  when:
    - 'INSTALL_SOURCE == "offline"'
    - "ansible_os_family == 'Debian'"

- name: Ensure rpcbind is running
  service: name=rpcbind state=started enabled=yes

- name: Wait NFS server to be up
  wait_for: timeout=300 port=2049 host="{{ item }}"
  with_items: "{{ groups['nfs-server'] }}"
