apiVersion: v1
kind: PersistentVolume
metadata:
  name: aiplatform-app-data-pv
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  mountOptions:
    - rsize=8192
    - timeo=14
    - intr
    - tcp
    - nfsvers=4.1
  nfs:
    server: master01
    path: /mnt/local/aiplatform-app-data/

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aiplatform-app-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
