apiVersion: v1
kind: PersistentVolume
metadata:
  name: aiplatform-model-data-pv
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  mountOptions:
    - rsize=8192
    - timeo=14
    - intr
    - tcp
  nfs:
    server: master
    path: /mnt/local/pvc/aiplatform-model-data

---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aiplatform-model-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aiplatform-model-data-pv-kfserving-pod
  namespace: kfserving-pod
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  mountOptions:
    - rsize=8192
    - timeo=14
    - intr
    - tcp
  nfs:
    server: master
    path: /mnt/local/pvc/aiplatform-model-data

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aiplatform-model-data-pvc-kfserving-pod
  namespace: kfserving-pod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

