group_labels:
  - group: kube-master
    labels:
      - mysql=active
      - postgres=active
      - grafana=active
      - prometheus=active
      - aiarts-backend=active
      - aiarts-frontend=active
      - alert-manager=active
      - image-label=active
      - jobmanager=active
      - restfulapi=active
      - webui=active
      - nginx=active
      - watchdog=active
      - webportal=active
      - mlflow=active
  - group: kube-worker
    labels:
      - worker=active
      - FragmentGPUJob=active
