# Project Name
PROJECT_NAME: "sz_gongdianju"

PLATFORM_NAME: "Apulis"

# the name of cluster
CLUSTER_NAME: "DLWS"

# 离线安装系统软件包 (offline|online)
INSTALL_SOURCE: "online"

# Binaries Directory
i18n: "zh-CN"

# kube vip address
kube_vip_address: "192.168.1.154"

nfs_path_prefix: /mnt/local/
