{% import 'macros/common.j2' as util with context %}

{% if service["prometheus"]["cluster_name"] is defined %}
{% set cluster_name = service["prometheus"]["cluster_name"] %}
{% else %}
{% set cluster_name = CLUSTER_NAME %}
{% endif %}

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: kube-system
data:
  prometheus.yml: |-
    global:
      external_labels:
        cluster: {{ CLUSTER_NAME }}
    rule_files:
      - "/etc/prometheus-alert/*.rules"
    scrape_configs:
    - job_name: 'serivce_exporter'
      scrape_interval: '30s'
      kubernetes_sd_configs:
      - role: pod
      tls_config:
        ca_file: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
      bearer_token_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          regex: true
          action: keep
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          regex: (.+)
          action: replace
          target_label: __metrics_path__
        - source_labels: [__meta_kubernetes_pod_host_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
          regex: '([^;]+);(\d+)'
          replacement: ${1}:${2}
          action: replace
          target_label: __address__
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          regex: 'prom-ign-.*'
          action: drop
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: scraped_from
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: replace
          target_label: exporter_name
    alerting:
      alertmanagers:
        - path_prefix: alert-manager
          tls_config:
            ca_file: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
          bearer_token_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
          kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ["kube-system"]
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_alert]
              regex: true
              action: keep
            - source_labels: [__meta_kubernetes_pod_host_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
              regex: '([^;]+);(\d+)'
              replacement: ${1}:${2}
              action: replace
              target_label: __address__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment-{{ arch_map[ansible_architecture] }}
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        task: monitoring
        app: prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: '{{service["prometheus"]["reporter"]["port"]}}'
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - grafana
                  - grafana-zh
            topologyKey: grafana
      nodeSelector:
        prometheus: active
        archType: {{ arch_map[ansible_architecture] }}
      hostNetwork: true
      initContainers:
      - name: init
        image: {{ util.image_fullname('bash', 'third') }}
        volumeMounts:
        - name: aiplatform-component-data-pvc
          mountPath:  /prometheus-data
          subPath: prometheus/ 
        command: ["chmod", "777", "/prometheus-data"] # newly create dir have permission 755, which makes prometheus container unable to write
      serviceAccountName: prometheus
      {% if service["private_docker_registry_username"] is defined %}
      imagePullSecrets:
      - name: svccred
      {% endif %}
      containers:
      - name: prometheus
        image: {{ util.image_fullname('prometheus', 'third') }}
        resources:
          limits:
            memory: "10Gi"
          requests:
            memory: "256Mi"
        args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--web.listen-address=0.0.0.0:{{service["prometheus"]["port"]}}'
          - '--web.external-url=http://localhost:{{service["prometheus"]["port"]}}/prometheus/'
          - '--web.route-prefix=prometheus'
          - '--storage.tsdb.path=/prometheus-data'
          - '--storage.tsdb.retention=365d'
        ports:
        - name: web
          containerPort: {{service["prometheus"]["port"]}}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: rules-volume
          mountPath: /etc/prometheus-alert
        - name: aiplatform-component-data-pvc
          mountPath: /prometheus-data
          subPath: prometheus/
      - name: gpu-reporter
        image: {{ util.image_fullname('gpu-reporter') }}
        args:
          - 'python'
          - '/gpu-reporter/reporter.py'
          - '--prometheus_url'
          - 'http://localhost:{{service["prometheus"]["port"]}}'
          - '--port'
          - '{{service["prometheus"]["reporter"]["port"]}}'
        ports:
        - name: reporter
          containerPort: {{service["prometheus"]["reporter"]["port"]}}
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-configmap
      - name: rules-volume
        configMap:
          name: prometheus-alert
      - name: aiplatform-component-data-pvc
        persistentVolumeClaim:
          claimName: aiplatform-component-data-pvc
      tolerations:
      - key: node.kubernetes.io/memory-pressure
        operator: "Exists"
      - key: node.kubernetes.io/disk-pressure
        operator: "Exists"
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
