- name: 准备{{manifest_dest}}/network目录
  file:
    path: "{{manifest_dest}}/network/"
    state: directory
    mode: 0755

- name: 下发weave-role.yaml文件
  copy:
    src: weave-role.yaml
    dest: "{{manifest_dest}}/network/01-weave-role.yaml"

- name: Render weave.yaml文件
  template:
    dest: "{{manifest_dest}}/network/02-weave.yaml"
    src: weave.yaml.j2
