- name: 下发weave-role.yaml文件
  copy:
    src: weavenet-role.yaml
    dest: /tmp/weave-role.yaml

- name: 初始化weave net role信息
  k8s:
    state: present
    src: /tmp/weave-role.yaml
  run_once: true

- name: Render weave.yaml文件
  template:
    dest: /tmp/weave.yaml
    src: weave.yaml.j2

- name: 初始化weave net
  k8s:
    state: present
    src: /tmp/weave.yaml
  run_once: true
