- name: 获得系统完整的版本号，例如 18.04.1
  set_fact: UBUNTU_VERSION={{ansible_lsb['description'].split(' ')[1]}}

# 离线安装 chrony
- name: 准备离线安装包目录
  file: name=/opt/kube/packages/chrony state=directory

# ubuntu 1604
- block:
    - name: 分发 chrony_xenial 离线包
      copy:
        src: "{{ resource_dir }}/apt/{{ arch_map[ansible_architecture] }}/chrony_xenial.tar.gz"
        dest: "/opt/kube/packages/chrony/chrony_xenial.tar.gz"

    - name: 安装 chrony_xenial 离线包
      shell: 'cd /opt/kube/packages/chrony && tar zxf chrony_xenial.tar.gz && \
             dpkg -i *.deb > /tmp/install_chrony.log 2>&1'
  when: ansible_distribution_release == "xenial"
  ignore_errors: true

# ubuntu 1804
- block:
    - name: 分发 chrony_{{UBUNTU_VERSION}} 离线包
      copy:
        src: "{{ resource_dir }}/apt/{{ arch_map[ansible_architecture] }}/chrony_{{UBUNTU_VERSION}}.tar.gz"
        dest: "/opt/kube/packages/chrony/chrony_{{UBUNTU_VERSION}}.tar.gz"

    - name: 安装 chrony_{{UBUNTU_VERSION}} 离线包
      shell: 'cd /opt/kube/packages/chrony && tar zxf chrony_{{UBUNTU_VERSION}}.tar.gz && \
             dpkg -i *.deb > /tmp/install_chrony.log 2>&1'
  ignore_errors: true
