# 离线安装 chrony
- name: 准备离线安装包目录
  file: name=/opt/kube/packages/chrony state=directory

# ubuntu 1604
- block:
    - name: 分发 chrony_xenial 离线包
      copy:
        src: "{{ base_dir }}/download/packages/chrony_xenial.tar.gz"
        dest: "/opt/kube/packages/chrony/chrony_xenial.tar.gz"

    - name: 安装 chrony_xenial 离线包
      shell: 'cd /opt/kube/packages/chrony && tar zxf chrony_xenial.tar.gz && \
             dpkg -i *.deb > /tmp/install_chrony.log 2>&1'
  when: ansible_distribution_release == "xenial"
  ignore_errors: true

# ubuntu 1804
- block:
    - name: 分发 chrony_bionic 离线包
      copy:
        src: "{{ base_dir }}/download/packages/chrony_bionic.tar.gz"
        dest: "/opt/kube/packages/chrony/chrony_bionic.tar.gz"

    - name: 安装 chrony_bionic 离线包
      shell: 'cd /opt/kube/packages/chrony && tar zxf chrony_bionic.tar.gz && \
             dpkg -i *.deb > /tmp/install_chrony.log 2>&1'
  when: ansible_distribution_release == "bionic"
  ignore_errors: true
