- name: 准备{{manifest_dest}}/network目录
  file:
    path: "{{manifest_dest}}/network/"
    state: directory
    mode: 0755

# DNS文件中部分参数根据hosts文件设置而定，因此需要用template模块替换参数
- name: 准备 DNS的部署文件
  template: src={{ item }}.yaml.j2 dest={{manifest_dest}}/network/20-{{ item }}.yaml
  with_items:
    - coredns
  when:
    - 'dns_install == "yes"'