- name: 准备{{manifest_dest}}/network目录
  file:
    path: "{{manifest_dest}}/network/"
    state: directory
    mode: 0755

- name: Create kube-vip config directory
  file:
    path: /etc/kube-vip
    state: directory
    mode: 0755

- name: Write kube-vip config file"
  template:
    src: config.yaml.j2
    dest: /etc/kube-vip/config.yaml

- name: Write static pod manifest
  template:
    src: kube-vip.yaml.j2
    dest: "{{manifest_dest}}/network/10-kube-vip.yaml"
    mode: 0600