- name: Create kube-vip config directory
  file:
    path: /etc/kube-vip
    state: directory
    mode: 0755

- name: Write kube-vip config file"
  template:
    src: config.yaml.j2
    dest: /etc/kube-vip/config.yaml

- name: Create kubelet static pod manifest directory
  file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: 0700

- name: Write static pod manifest
  template:
    src: kube-vip.yaml.j2
    dest: /etc/kubernetes/manifests/kube-vip.yaml
    mode: 0600