- name: 准备{{manifest_dest}}/network目录
  file:
    path: "{{manifest_dest}}/network/"
    state: directory
    mode: 0755

- name: Create kube-vip config directory
  file:
    path: /etc/kube-vip
    state: directory
    mode: 0755

- name: Write kube-vip config file"
  template:
    src: config.yaml.j2
    dest: /etc/kube-vip/config.yaml

- name: Write static pod manifest
  template:
    src: kube-vip.yaml.j2
    dest: "{{manifest_dest}}/network/10-kube-vip.yaml"
    mode: 0600

# 只需单节点执行一次
- name: 运行 weave 网络
  shell: "{{ bin_dir }}/kubectl apply -f {{manifest_dest}}/network/10-kube-vip.yaml"

- block:
    - name: 替换 kubeconfig 的 apiserver 地址
      lineinfile:
        dest: "{{ item }}"
        regexp: "^    server"
        line: "    server: https://{{ kube_vip_address }}:6443"
      with_items:
        - "/root/.kube/config"
        - "/home/{{user_name}}/.kube/config"
        - "/etc/kubernetes/kubelet.kubeconfig"
        - "/etc/kubernetes/kube-proxy.kubeconfig"

    - name: restart kube-worker service
      service: name={{ item }} state=restarted
      with_items:
        - kubelet
        - kube-proxy
      ignore_errors: true
  when: "inventory_hostname in groups['kube-worker']"