# server or client
ceph_mode: server

rook_pv_pvc_mounts:
  app-data:
    storageClassName: app-data
    name: aiplatform-app-data
    rootPath: /pvc/aiplatform-app-data
  component-data:
    storageClassName: component-data
    name: aiplatform-component-data
    rootPath: /pvc/aiplatform-component-data
  label-data:
    storageClassName: label-data
    name: aiplatform-label-data
    rootPath: /pvc/aiplatform-label-data
  model-data:
    storageClassName: model-data
    name: aiplatform-model-data
    rootPath: /pvc/aiplatform-model-data
  kfserving-pod-model-data:
    storageClassName: model-data
    name: aiplatform-model-data
    rootPath: /pvc