- name: Ensure directories to export exist
  file:  # noqa 208
    path: "{{ item.path }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: export the directories editing the file /etc/exports
  lineinfile: dest=/etc/exports regexp="^{{ item.0.path }} " line="{{ item.0.path }} {{hostvars[item.1]['ansible_default_ipv4'].address}}{{ item.0.exportOpts }}" create=yes
  with_subelements:
    - "{{ nfs_exports }}"
    - clients
  register: nfs_exports_result

- include: "nfs-server-{{ansible_os_family}}.yaml"

- name: Ensure rpcbind is running
  service: name=rpcbind state=started enabled=yes
  when: not nfs_only_v4

- name: Restart NFS server service
  service: name={{NFS_SERVICE}} state=restarted enabled=yes
  when: nfs_exports_result is changed

- name: Check if NFS server service is started
  service: name={{NFS_SERVICE}} state=started

- name: Ensure rpcbind is stopped
  service: name=rpcbind state=stopped enabled=no
  when: nfs_only_v4

- name: Ensure rpcbind.socket is stopped
  service: name=rpcbind.socket state=stopped enabled=no
  when: ansible_os_family == "RedHat" and nfs_only_v4
