- name: update repositories cache and install NFS in Deb systems
  apt: name=nfs-kernel-server,nfs-common update_cache=yes cache_valid_time=3600

- set_fact: NFS_SERVICE="nfs-kernel-server"

- block:
    - name: Set NEED_STATD
      lineinfile:
        dest: /etc/default/nfs-common
        regexp: '^NEED_STATD='
        line: NEED_STATD="no"

    - name: Set NEED_IDMAPD
      lineinfile:
        dest: /etc/default/nfs-common
        regexp: '^NEED_IDMAPD='
        line: NEED_IDMAPD="yes"

    - name: Set RPCNFSDOPTS
      lineinfile:
        dest: /etc/default/nfs-kernel-server
        regexp: '^RPCNFSDOPTS='
        line: RPCNFSDOPTS="-N 2 -N 3"

    - name: Set RPCMOUNTDOPTS
      lineinfile:
        dest: /etc/default/nfs-kernel-server
        regexp: '^RPCMOUNTDOPTS='
        line: RPCMOUNTDOPTS="--manage-gids -N 2 -N 3"

  when: nfs_only_v4 | bool