- name: 获取是否已经安装docker
  shell: 'systemctl status docker|grep Active || echo "NoFound"'
  register: docker_svc

# 18.09.x 版本二进制名字有变化，需要做判断
- name: 获取docker版本信息
  shell: "{{ base_dir }}/bin/{{ arch_map[ansible_architecture] }}/dockerd --version|cut -d' ' -f3"
  register: docker_ver
  connection: local
  run_once: true
  tags: upgrade_docker, download_docker

- name: debug info
  debug:
    var: "docker_ver"
  tags: upgrade_docker, download_docker

- name: 转换docker版本信息为浮点数
  set_fact:
    DOCKER_VER: "{{ docker_ver.stdout.split('.')[0]|int + docker_ver.stdout.split('.')[1]|int/100 }}"
  tags: upgrade_docker, download_docker

- name: debug info
  debug:
    var: "DOCKER_VER"
  tags: upgrade_docker, download_docker

# 判断nvidia显卡是否存在
- name: 判断nvidia显卡是否存在
  shell: "nvidia-smi"
  register: NVIDIA_VAR
  ignore_errors: true

- block:
    - name: 准备docker相关目录
      file: name={{ item }} state=directory
      with_items:
        - "{{ bin_dir }}"
        - /etc/docker
        - /root/.docker

    - name: 下载 docker 二进制文件(>= 18.09.x)
      copy: src={{ base_dir }}/bin/{{ arch_map[ansible_architecture] }}/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
        - containerd
        - containerd-shim
        - docker-init
        - runc
        - docker
        - ctr
        - dockerd
        - docker-proxy
      tags: upgrade_docker, download_docker
      when: "DOCKER_VER|float >= 18.09"

    - name: docker国内镜像加速
      template: src=daemon.json.j2 dest=/etc/docker/daemon.json
      when: NVIDIA_VAR.rc != 0

    - name: docker国内镜像加速
      template: src=gpu.daemon.json.j2 dest=/etc/docker/daemon.json
      when: NVIDIA_VAR.rc == 0

    - name: flush-iptables
      shell: "iptables -P INPUT ACCEPT \
        && iptables -F && iptables -X \
        && iptables -F -t nat && iptables -X -t nat \
        && iptables -F -t raw && iptables -X -t raw \
        && iptables -F -t mangle && iptables -X -t mangle"

    - name: 创建docker的systemd unit文件
      template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
      tags: upgrade_docker, download_docker

    - name: docker的experimental 配置
      copy: src=config.json dest=/root/.docker/config.json

    - name: 开机启用docker 服务
      shell: systemctl enable docker
      ignore_errors: true

    - name: 开启docker 服务
      shell: systemctl daemon-reload && systemctl restart docker
      tags: upgrade_docker

    - name: 轮询等待docker服务运行
      shell: "systemctl status docker.service|grep Active"
      register: docker_status
      until: '"running" in docker_status.stdout'
      retries: 8
      delay: 2
      tags: upgrade_docker
  when: "'running' not in docker_svc.stdout"
