# 创建harbor仓库
- import_tasks: init.yaml

- name: 下载镜像tar文件
  copy: src={{ item }} dest={{HARBOR_LOCATION}}/images/
  with_fileglob:
    - "{{ base_dir }}/resources/images/*.tar"

- name: Docker登录harbor - {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}
  command:
    cmd: "{{bin_dir}}/docker login {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}} \
      -u admin -p {{ lookup('file', '{{ base_dir }}/credentials/harbor.pwd') }}"
  register: login_result

- name: 创建 {{ PROJECT_NAME }} 工程
  uri:
    url: https://{{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/api/v2.0/projects
    method: POST
    validate_certs: false
    return_content: yes
    user: "admin"
    password: "{{ lookup('file', '{{ base_dir }}/credentials/harbor.pwd') }}"
    force_basic_auth: yes
    status_code: [200, 201, 409]
    body: '{"project_name":"{{PROJECT_NAME}}","metadata":{"public":"true"},"storage_limit":-1}'
    body_format: json
  when: '"Login Succeeded" in login_result.stdout'

- include: push.yaml image="{{HARBOR_LOCATION}}/images/{{ item | basename }}"
  with_fileglob:
    - "{{ base_dir }}/resources/images/*.tar"
  when: '"Login Succeeded" in login_result.stdout'

- name: 暂存已经到push到harbor的镜像到另外一个地方
  shell: "mv {{item}} {{ base_dir }}/resources/images-pushed/{{ item | basename }}"
  connection: local
  with_fileglob:
    - "{{ base_dir }}/resources/images/*.tar"
  when: '"Login Succeeded" in login_result.stdout'
