- name: Load Docker镜像本地
  command:
    cmd: "{{bin_dir}}/docker load -i {{ image }}"
  register: result

- name: 解析镜像信息(name，arch和tag等)
  set_fact:
    manifest_name: '{{ (line.split(":")[1:-1] | join(":") | trim).split("/")[2:-1] | join("/") }}'
    orig_name: '{{ line.split(":")[1:] | join(":") | trim }}'
    tag: '{{ line.split(":")[-1] | trim }}'
  with_items: "{{ result.stdout_lines }}"
  when: '"Loaded image" in line'
  loop_control:
    loop_var: line

- name: 推送AMD64镜像 {{ orig_name }} 到harbor
  shell: "
        {{bin_dir}}/docker tag {{orig_name}} {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_amd64:{{tag}} && \
        {{bin_dir}}/docker push {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_amd64:{{tag}}; \
        {{bin_dir}}/docker manifest create {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}:{{tag}} \
            {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_amd64:{{tag}} || \
      	{{bin_dir}}/docker manifest create {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}:{{tag}} \
      	    {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_amd64:{{tag}} -a; \
      	{{bin_dir}}/docker manifest annotate {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}:{{tag}} \
      		{{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_amd64:{{tag}} --os linux --arch amd64 && \
      	{{bin_dir}}/docker manifest push {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}:{{tag}}
        "
  when: '"amd64" in orig_name'

- name: 推送ARM64镜像 {{ orig_name }} 到harbor
  shell: "
        {{bin_dir}}/docker tag {{orig_name}} {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_arm64:{{tag}} && \
        {{bin_dir}}/docker push {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_arm64:{{tag}}; \
        {{bin_dir}}/docker manifest create {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}:{{tag}} \
            {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_arm64:{{tag}} || \
        {{bin_dir}}/docker manifest create {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}:{{tag}} \
            {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_arm64:{{tag}} -a; \
        {{bin_dir}}/docker manifest annotate {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}:{{tag}} \
            {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}_arm64:{{tag}} --os linux --arch arm64 && \
        {{bin_dir}}/docker manifest push {{HARBOR_DOMAIN}}:{{ HARBOR_HTTPS_PORT}}/{{ PROJECT_NAME }}/{{ manifest_name }}:{{tag}}
        "
  when: '"arm64" in orig_name'

- name: 暂存{{ image | basename}}镜像到另外一个地方
  shell: "mv {{ base_dir }}/resources/images/{{ image | basename }} {{ base_dir }}/resources/images-pushed/{{ image | basename }}"
  connection: local