{
 "title": "DLTS VC统计",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "vc_name",
    "label": "vc_name",
    "query": "label_values(k8s_vc_device_total, vc_name)"
   }
  ]
 },
 "panels": [
  { "title": "GPUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "已分配",
   "type": "singlestat",
   "description": "分配给VC的设备数量",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "可分配的",
   "type": "singlestat",
   "description": "Number of GPUs immediately assignable to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_available{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "不良",
   "type": "singlestat",
   "description": "Number of unhealthy GPUs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_unschedulable{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "已分配",
   "type": "singlestat",
   "description": "Number of GPUs assigned to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count ( avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "活动",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count( avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "闲置",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization 0% in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "NPUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "已分配",
   "type": "singlestat",
   "description": "分配给VC的设备数量",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "可分配的",
   "type": "singlestat",
   "description": "Number of GPUs immediately assignable to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_available{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "不良",
   "type": "singlestat",
   "description": "Number of unhealthy GPUs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_device_unschedulable{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "已分配",
   "type": "singlestat",
   "description": "Number of GPUs assigned to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (instance,uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "活动",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "空闲",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization 0% in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "随时间推移的设备", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "设备",
   "type": "graph",
   "description": "VC中随时间变化的GPU数量",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})",
     "legendFormat": "Allocated GPU"
    },
    {
     "expr": "avg(k8s_vc_device_available{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})",
     "legendFormat": "可分配的GPU"
    },
    {
     "expr": "avg(k8s_vc_device_unschedulable{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})",
     "legendFormat": "不可调度的GPU"
    },
    {
     "expr": "count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)",
     "legendFormat": "Assigned GPU"
    },
    {
     "expr": "count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)",
     "legendFormat": "活动的GPU"
    },
    {
     "expr": "(count( avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0))",
     "legendFormat": "空闲的 GPU"
    },
    {
     "expr": "avg(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Allocated NPU"
    },
    {
     "expr": "avg(k8s_vc_device_available{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})",
     "legendFormat": "可分配的NPU"
    },
    {
     "expr": "avg(k8s_vc_device_unschedulable{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})",
     "legendFormat": "不可调度的NPU"
    },
    {
     "expr": "count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)",
     "legendFormat": "Assigned NPU"
    },
    {
     "expr": "count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)",
     "legendFormat": "活动的NPU"
    },
    {
     "expr": "(count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))",
     "legendFormat": "空闲的NPU"
    }
   ]
  },
  { "title": "GPU使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "已分配的GPU使用率",
   "type": "singlestat",
   "description": "分配给VC的所有GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / sum(avg by (instance)(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}))"
    }
   ]
  },
  {
   "title": "随着时间分配的GPU使用率",
   "type": "singlestat",
   "description": "在选定的时间范围内，VC中所有GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / sum(avg by (instance) (k8s_vc_device_total{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}))"
    }
   ]
  },
  {
   "title": "已分配的GPU使用率",
   "type": "singlestat",
   "description": "VC中所有已分配GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "随着时间分配的GPU使用率",
   "type": "singlestat",
   "description": "在选定时间范围内，VC中所有已分配GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "活动的GPU使用率",
   "type": "singlestat",
   "description": "VC中所有活动GPU(>0%)的平均GPU利用率。",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  {
   "title": "随着时间活动的GPU使用率",
   "type": "singlestat",
   "description": "在选定时间范围内，VC中所有活动GPU(>0%)的平均GPU利用率。",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  { "title": "NPU使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "分配的NPU使用率",
   "type": "singlestat",
   "description": "分配给VC的所有GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / sum(avg by (instance)(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}))"
    }
   ]
  },
  {
   "title": "随着时间分配的NPU使用率",
   "type": "singlestat",
   "description": "在选定的时间范围内，VC中所有GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / sum(avg by (instance)(k8s_vc_device_total{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}))"
    }
   ]
  },
  {
   "title": "分配的NPU使用率",
   "type": "singlestat",
   "description": "VC中所有已分配GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "随着时间分配的NPU使用率",
   "type": "singlestat",
   "description": "在选定时间范围内，VC中所有已分配GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "活动的NPU使用率",
   "type": "singlestat",
   "description": "VC中所有活动GPU(>0%)的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  {
   "title": "随着时间推移主动NPU使用率",
   "type": "singlestat",
   "description": "在选定时间范围内，VC中所有活动GPU(>0%)的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  { "title": "随着时间活动的设备使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "设备使用率",
   "type": "graph",
   "description": "随着时间的推移，VC中平均GPU利用率",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / sum(avg by (instance)(k8s_vc_device_total{device_str='nvidia.com/gpu'}))",
     "legendFormat": "Allocated GPU"
    },
    {
     "expr": "avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})",
     "legendFormat": "Assigned GPU"
    },
    {
     "expr": "avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)",
     "legendFormat": "Active GPU"
    },
    {
     "expr": "sum(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / sum(avg by (instance)(k8s_vc_device_total{device_str='npu.huawei.com/NPU'}))",
     "legendFormat": "Allocated NPU"
    },
    {
     "expr": "avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})",
     "legendFormat": "Assigned NPU"
    },
    {
     "expr": "avg by (uuid) (task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)",
     "legendFormat": "Active NPU"
    }
   ]
  },
  { "title": "每个活动设备的资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "GPU内存",
   "type": "singlestat",
   "description": "VC中所有活动GPU(>0%)的平均GPU内存利用率",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 53 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "NPU内存",
   "type": "singlestat",
   "description": "VC中所有活动GPU(0%)的平均GPU内存利用率",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 53 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "Average CPU usage per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_cpu_percent.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (avg by (instance)(task_cpu_percent{vc_name=\"$vc_name\"})) / count(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "内存",
   "type": "singlestat",
   "description": "Average memory usage per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_mem_usage_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 53 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance)(task_mem_usage_byte{vc_name=\"$vc_name\"})) / count(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "磁盘读取",
   "type": "singlestat",
   "description": "Average disk read rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_block_in_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 53 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance)(rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "磁盘写入",
   "type": "singlestat",
   "description": "Average disk write rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_block_out_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 53 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance)(rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "网络输入",
   "type": "singlestat",
   "description": "Average network inbound rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_net_in_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 53 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance)(rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "网络输出",
   "type": "singlestat",
   "description": "Average network outbound rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_net_out_byte.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 53 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (instance)(rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  { "title": "随着时间推移每个活动设备的资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "每个活动设备的设备内存",
   "type": "graph",
   "description": "每个活动GPU的平均GPU内存利用率",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance,uuid)((task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "vc(GPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid)((task_device_percent{device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{device_str='nvidia.com/gpu'})) / count(avg by (instance,uuid)(task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster(GPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid)((task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "vc(NPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid)((task_device_percent{device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{device_str='npu.huawei.com/NPU'})) / count(avg by (instance,uuid)(task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster(NPU)"
    }
   ]
  },
  {
   "title": "每个活动设备的CPU",
   "type": "graph",
   "description": "Average CPU usage per active GPU.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance)(task_cpu_percent{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) / 100) OR on() vector(0)",
     "legendFormat": "vc(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(task_cpu_percent)) / count(avg by (instance,uuid)(task_device_percent{device_str='nvidia.com/gpu'}>0)) / 100) OR on() vector(0)",
     "legendFormat": "Cluster(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(task_cpu_percent{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) / 100) OR on() vector(0)",
     "legendFormat": "vc(NPU)"
    },
    {
     "expr": "(sum(avg by (instance)(task_cpu_percent)) / count(avg by (instance,uuid)(task_device_percent{device_str='npu.huawei.com/NPU'}>0)) / 100) OR on() vector(0)",
     "legendFormat": "Cluster(NPU)"
    }
   ]
  },
  {
   "title": "每个设备的内存使用率",
   "type": "graph",
   "description": "Average memory usage per active GPU.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance)(task_mem_usage_byte{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "vc(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(task_mem_usage_byte)) / count(avg by (instance,uuid)(task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(task_mem_usage_byte{vc_name=\"$vc_name\"})) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "vc(NPU)"
    },
    {
     "expr": "(sum(avg by (instance,uuid)(task_mem_usage_byte)) / count(avg by (instance,uuid)(task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster(NPU)"
    }
   ]
  },
  {
   "title": "每个活动设备的磁盘I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance)(rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_block_in_byte[5m]))) / count(avg by (instance,uuid)(task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_block_out_byte[5m]))) / count(avg by (instance,uuid)(task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(NPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_block_in_byte[5m]))) / count(avg by (instance,uuid)(task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_block_out_byte[5m]))) / count(avg by (instance,uuid)(task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster Out(NPU)"
    }
   ]
  },
  {
   "title": "每个活动设备的网络I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(avg by (instance)(rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_net_in_byte[5m]))) / count(avg by (instance,uuid)(task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster In(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_net_out_byte[5m]))) / count(avg by (instance,uuid)(task_device_percent{device_str='nvidia.com/gpu'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster Out(GPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m]))) / count(avg by (instance,uuid)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "VC Out(NPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_net_in_byte[5m]))) / count(avg by (instance,uuid)(task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster In(NPU)"
    },
    {
     "expr": "(sum(avg by (instance)(rate(task_net_out_byte[5m]))) / count(avg by (instance,uuid)(task_device_percent{device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)",
     "legendFormat": "Cluster Out(NPU)"
    }
   ]
  },
  { "title": "用户", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "用户分配的设备",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(avg by (instance,uuid,username)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'})) by (username)",
     "legendFormat": "{{username}}(GPU)"
    },
    {
     "expr": "count(avg by (instance,uuid,username)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'})) by (username)",
     "legendFormat": "{{username}}(NPU)"
    }
   ]
  },
  {
   "title": "用户分配的设备使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}) by (username)",
     "legendFormat": "{{username}}(GPU)"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}) by (username)",
     "legendFormat": "{{username}}(NPU)"
    }
   ]
  },
  {
   "title": "用户活动设备",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(avg by (instance,uuid,username)(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0)) by (username)",
     "legendFormat": "{{username}}(GPU)"
    },
    {
     "expr": "count(avg by (instance,uuid,username)(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0)) by (username)",
     "legendFormat": "{{username}}(NPU)"
    }
   ]
  },
  {
   "title": "用户的主动设备使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='nvidia.com/gpu'}>0) by (username)",
     "legendFormat": "{{username}}(GPU)"
    },
    {
     "expr": "avg(task_device_percent{vc_name=\"$vc_name\",device_str='npu.huawei.com/NPU'}>0) by (username)",
     "legendFormat": "{{username}}(NPU)"
    }
   ]
  }
 ]
}