{
 "title": "DLTS任务统计",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job_name",
    "label": "job_id",
    "query": "label_values(task_cpu_percent, job_name)"
   }
  ]
 },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "已分配的GPU",
   "type": "singlestat",
   "description": "Number of GPUs assigned to the job.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "活动的GPU",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "空闲的GPU",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "NPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "已分配的NPU",
   "type": "singlestat",
   "description": "Number of NPUs assigned to the job.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "活动的NPU",
   "type": "singlestat",
   "description": "Number of active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "空闲的NPU",
   "type": "singlestat",
   "description": "Number of active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'})) OR on() vector(0)) - (count(avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>0)) OR on() vector(0))"
    }
   ]
  },
  { "title": "GPU使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "已分配的GPU使用率",
   "type": "singlestat",
   "description": "作业中所有分配GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "随着时间分配的GPU使用率",
   "type": "singlestat",
   "description": "在选定的时间范围内，作业中所有分配GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'})"
    }
   ]
  },
  {
   "title": "活动的GPU使用率",
   "type": "singlestat",
   "description": "作业中所有活动GPU(>0%)的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  {
   "title": "随着时间活动的积极利用",
   "type": "singlestat",
   "description": "在选定的时间范围内，作业中所有活动GPU的平均GPU利用率",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>=0)"
    }
   ]
  },
  { "title": "NPU使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "分配的NPU使用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs in the job.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "随着时间分配的NPU使用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all assigned NPUs in the job in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'})"
    }
   ]
  },
  {
   "title": "活动的NPU使用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  {
   "title": "随着时间推移主动NPU使用率",
   "type": "singlestat",
   "description": "Average NPU utilization across all active NPUs (>0%) in the job over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>=0)"
    }
   ]
  },
  { "title": "每个活动设备的资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "GPU内存",
   "type": "singlestat",
   "description": "Average NPU memory utilization across all active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(avg by (uuid) ((task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'} > bool 0) * task_device_mem_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'})) / count( avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "NPU内存",
   "type": "singlestat",
   "description": "Average NPU memory utilization across all active NPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum( avg by (uuid) ((task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'} > bool 0) * task_device_mem_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'})) / count( avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "CPU usage per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 29 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{job_name=\"$job_name\"}) / count( avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0)) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "内存",
   "type": "singlestat",
   "description": "Memory usage per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 29 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte{job_name=\"$job_name\"}) / count( avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "磁盘读取",
   "type": "singlestat",
   "description": "Block In Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 29 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte{job_name=\"$job_name\"}[5m])) / count( avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "磁盘写入",
   "type": "singlestat",
   "description": "Block Out Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 29 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_out_byte{job_name=\"$job_name\"}[5m])) / count( avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0)))OR on() vector(0)"
    }
   ]
  },
  {
   "title": "网络输入",
   "type": "singlestat",
   "description": "Network In Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 29 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte{job_name=\"$job_name\"}[5m])) / count( avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "网络输出",
   "type": "singlestat",
   "description": "Network Out Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 29 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_out_byte{job_name=\"$job_name\"}[5m])) / count( avg by (uuid) (task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}>0))) OR on() vector(0)"
    }
   ]
  },
  { "title": "时间序列", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "设备使用率",
   "type": "graph",
   "description": "Device utilization for all GPUs in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}) by (minor_number, instance)",
     "legendFormat": "GPU {{minor_number}} 在 {{instance}}"
    },
    {
     "expr": "avg(task_device_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}) by (minor_number, instance)",
     "legendFormat": "NPU {{minor_number}} 在 {{instance}}"
    }
   ]
  },
  {
   "title": "设备内存使用率",
   "type": "graph",
   "description": "Device memory utilization for all Devices in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_device_mem_percent{job_name=\"$job_name\",device_str='nvidia.com/gpu'}) by (minor_number, instance)",
     "legendFormat": "GPU {{minor_number}} 在 {{instance}}"
    },
    {
     "expr": "avg(task_device_mem_percent{job_name=\"$job_name\",device_str='npu.huawei.com/NPU'}) by (minor_number, instance)",
     "legendFormat": "NPU {{minor_number}} 在 {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_cpu_percent{job_name=\"$job_name\"}) by (instance)",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "内存",
   "type": "graph",
   "description": "Memory usage in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(task_mem_usage_byte{job_name=\"$job_name\"}) by (instance)",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "磁盘I/O",
   "type": "graph",
   "description": "Disk IO rate in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_block_in_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{instance}} 写入"
    },
    {
     "expr": "sum(rate(task_block_out_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{instance}} 释放"
    }
   ]
  },
  {
   "title": "网络I/O",
   "type": "graph",
   "description": "Network I/O rate in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_net_in_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{instance}} 写入"
    },
    {
     "expr": "sum(rate(task_net_out_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{instance}} 释放"
    }
   ]
  }
 ]
}