apiVersion: v1
data:
  config.yaml: |+
    port: 9000

    log:
      writefile: true
      filedir: logs
      filename: ai_arts_backend.log

    database: postgres
    db:
      mysql:
        username: root
        password: 4Tka6kDR8Kgy455O
        host: mysql.kube-system
        port: 3306
        database: ai_arts
        maxopenconns: 10
        maxidleconns: 2
      postgresql:
        username: postgres
        password: 36wFZvf8suFgfdyY
        host: postgres.kube-system
        port: 5432
        database: ai_arts
        maxopenconns: 10
        maxidleconns: 2

    file:
      datasetdir: /data/dataset
      modeldir: /data/model
      sizelimit: 1000000000

    Anno:
      backendUrl: http://conip/data-platform-backend

    Infer:
      backendUrl: http://conip

    auth:
      url: http://conip:80/
      key: "Sign key for JWT"

    DltsUrl: http://conip:80/apis
    TrackingUrl: http://localhost:9010/api/2.0/mlflow
    image:
      tensorflow:
        - image: apulistech/ubuntu:18.04-amd64
          desc: "测试1"
          category: "normal"
        - image: apulistech/tensorflow:2.3.0-gpu-py3
          desc: "测试2"
          category: "normal"
        - image: apulistech/tensorflow:1.14.0-gpu-py3
          desc: "测试3"
          category: "normal"
        - image: apulistech/tensorflow:1.15.2-gpu-py3
          desc: "测试4"
          category: "normal"
        - image: apulistech/tf:1.15-arm-rc1
          desc: "测试5"
          category: "normal"
      pytorch:
        - image: apulistech/pytorch:1.5
          desc: "测试6"
          category: "normal"
      mxnet:
        - image: apulistech/mxnet:2.0.0-gpu-py3
          desc: "测试7"
          category: "normal"
      mindspore:
        - image: apulistech/mindspore:0.2.0-alpha
          desc: "测试8"
          category: "normal"
      caffe:
        - image: apulistech/caffe:BVLC
          desc: "测试9"
          category: "normal"
      hyperparameters:
        - image: apulistech/hyperparameters:tf1.15.0
          desc: "测试9"
          category: "hyperparameters"
        - image: apulistech/hyperparameters:tf2.3.0
          desc: "测试9"
          category: "hyperparameters"
        - image: apulistech/hyperparameters:pytorch1.6.0
          desc: "测试9"
          category: "hyperparameters"

    InteractiveModeJob: false
    PrivateRegistry: harbor.apulis.cn:8443/aiarts_v1.5.0_rc8/
    imagesave:
      k8sconf: /root/.kube/config
      sshkey: /root/.ssh/id_rsa
      sshuser: dlwsadmin
      sshport: 22


kind: ConfigMap
metadata:
  creationTimestamp: null
  name: aiarts-cm
