- name: Ensure /etc/nginx/ssl/ directory exists
  file:
    path: '/etc/nginx/{{item}}'
    state: directory
  with_items:
    - ssl
    - conf.other
    - fqdn

- name: copy ssl 证书
  copy:
    src: "{{ base_dir }}/manifests/services/nginx/ssl/{{item}}"
    dest: "/etc/nginx/ssl/{{item}}"
  with_items:
    - aiarts.crt
    - aiarts.key

- name: 拷贝nginx 配置文件
  copy:
    src: "{{ base_dir }}/manifests/services/nginx/default.conf"
    dest: "/etc/nginx/conf.other/default.conf"
