- name: "开启{{ PLATFORM_MODE}}类型服务列表"
  include: start-k8s.yaml service={{item | trim }}
  with_items: "{{modes[PLATFORM_MODE]}}"
  when: "{{ service_name == '' }}"
  tags: aiarts_start

- name: "开启{{ service_name}}服务"
  include: start-k8s.yaml service={{service_name}}
  when: "{{ service_name != '' }}"
  tags: aiarts_start
