{% import 'macros/common.j2' as util with context %}

{% if false %}
apiVersion: v1
kind: Service
metadata:
  name: webui3
  namespace: default
spec:
  ports:
  - port: {{service["webuiport"]}}
  selector:
    app: webui3
---
{% endif %}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: webui3
  namespace: default
spec:
  selector:
    matchLabels:
      webportal-node: pod
  template:
    metadata:
      name: webui3
      labels:
        app: webui3
        webportal-node: pod
    spec:
      {{util.dns_policy()}}
      nodeSelector:
        archType: {{ arch_map[ansible_architecture] }}
        webportal: active
      {% if true %}  
      hostNetwork: true
      {% endif %}
      containers:
      - name: webui3
        image: {{ util.image_name('webui3') }}
        imagePullPolicy: Always
        {% if false %}
        ports:
          - name: webui3
            containerPort: {{service["webuiport"]}}
        {% endif %}
        volumeMounts:
        - mountPath: /WebUI
          name: webuiconfig
        - mountPath: /usr/src/app/config
          name: nodejsconfig
        - mountPath: /var/log/webui3
          name: webuilog
      volumes:
      - name: webuiconfig
        configMap:
          name: webui-cm
      - name: webuilog
        hostPath:
          path: /var/log/webui3
      - name: nodejsconfig
        configMap:
          name: webui-cm
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        effect: NoSchedule            
